### ISSUE TITLE
Just suggestions

### ISSUE THREAD

**Issue by rcrooks** [siberia-theme/vscode#1]
Hi @pav-shatalov - I really do love this theme. Just have two suggestions for minor adjustments:

- increase the contrast a little for background of selected text
- make comments just a little brighter

Thanks for considering - I'll keep using Siberia regardless.

**Comment by pav-shatalov** [comment]
Glad theme works for you. Increased brightness for comments on 4 steps and selection for 2 steps. Will see how it works

**Comment by rcrooks** [comment]
Thank you!
